version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - "80:8888"
  macaque.cyrhades.fr:
    image: anssi/fcsc2021-crypto-macaque:latest
    ports:
      - "4000:4000"
